# set base image (host OS)
FROM {base}:latest as base

# ARG http_proxy
# ARG https_proxy
# ARG no_proxy
ARG AZURE_OPENAI_ENDPOINT
ARG AZURE_OPENAI_API_KEY
ARG RAG_VERSION_DIR
ARG CHAT_STORAGE_DIR
ARG DEPLOYMENT_TYPE
ARG MODEL_CACHE
ARG AUTHORIZATION_ENDPOINT
ARG TOKEN_ENDPOINT
ARG JWKS_URI
ARG REDIRECT_URI
ARG CLIENT_ID
ARG CLIENT_SECRET
ARG SCOPE
ARG AUDIENCE

# ENV http_proxy ${http_proxy}
# ENV https_proxy ${https_proxy}
# ENV no_proxy ${no_proxy}
ENV AZURE_OPENAI_ENDPOINT ${AZURE_OPENAI_ENDPOINT}
ENV AZURE_OPENAI_API_KEY ${AZURE_OPENAI_API_KEY}
ENV RAG_VERSION_DIR ${RAG_VERSION_DIR}
ENV DEPLOYMENT_TYPE ${DEPLOYMENT_TYPE}
ENV MODEL_CACHE ${MODEL_CACHE}
ENV AUTHORIZATION_ENDPOINT ${AUTHORIZATION_ENDPOINT}
ENV TOKEN_ENDPOINT ${TOKEN_ENDPOINT}
ENV JWKS_URI ${JWKS_URI}
ENV REDIRECT_URI ${REDIRECT_URI}
ENV CLIENT_ID ${CLIENT_ID}
ENV CLIENT_SECRET ${CLIENT_SECRET}
ENV SCOPE ${SCOPE}
ENV AUDIENCE ${AUDIENCE}

WORKDIR /app
COPY . /app

# Expose the prediction app through port 8501
EXPOSE 8501

# command to run on container start
CMD streamlit run Welcome.py
